// <auto-generated />
using System;
using EFCoreDemo1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreDemo1.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EFCoreDemo1.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    b.Property<string>("AuthName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("作者名");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasComment("价格");

                    b.Property<DateTime>("PubTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("发布日期");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("标题");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("T_Books", null, t =>
                        {
                            t.HasComment("书本表");
                        });
                });

            modelBuilder.Entity("EFCoreDemo1.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("主键");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasComment("年龄");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("出生地");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("名字");

                    b.HasKey("Id");

                    b.ToTable("T_Person", null, t =>
                        {
                            t.HasComment("角色表");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
